<?php
// $Id$

/**
 * @file
 * Main file for the Design review module
 */

/**
 * Implementation of hook_menu().
 */
function civimobile_menu() {
  $items = array();

  $items['civimobile'] = array(
    'title'            => 'CiviMobile',
    'description'      => 'A small but very effective mobile interface to your CiviCRM installation.',
    'page callback'    => '_civimobile_page',
    'access arguments' => array('access CiviCRM'),
    'type'             => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Callback for menu item civimobile
 */
function _civimobile_page() {
  $civimobile_page_settings = _civimobile_vars_setup();
  include_once(drupal_get_path('module','civimobile').'/templates/civimobile.page.tpl.php');
  
}


function _civimobile_vars_setup() {
    
    $civimobile_vars['language'] = $GLOBALS['locale'];
    $civimobile_vars['title']   = 'CiviMobile';
    $civimobile_vars['head']    = drupal_get_html_head();
    $civimobile_vars['favicon'] = theme_get_setting("toggle_favicon") ? "<link rel=\"shortcut icon\" href=\"". theme_get_setting("favicon") ."\" type=\"image/x-icon\"/>\n" : "";
    $civimobile_vars['styles']   = drupal_get_css();
    $civimobile_vars['scripts']   = drupal_get_js();
    $civimobile_vars['civimobile_assets']   = drupal_get_path('module','civimobile');
    
    return $civimobile_vars;     
}



