<?php
// $Id$

/**
 * @file
 * Main file for the Design review module
 */

/**
 * Implementation of hook_menu().
 */
function civimobile_menu() {
  $items = array();

  $items['civimobile'] = array(
    'title'            => 'CiviMobile',
    'description'      => 'A small but very effective mobile interface to your CiviCRM installation.',
    'page callback'    => '_civimobile_page',
    'access arguments' => array('access CiviCRM'),
    'type'             => MENU_NORMAL_ITEM,
  );

  return $items;
}


function civimobile_preprocess_page(&$variables){
	     $variables['styles'] = drupal_get_css();
}


function civimobile_theme() {
    return array (
        'civimobile_page' => array (
            'template' => 'civimobile.page',
            'arguments' => array('text' => NULL),
            )
    );    
}


/**
 * Callback for menu item civimobile
 */
function _civimobile_page() {
	drupal_add_css('path/to/style.css');
    return t('CiviMobile Homepage');
}


